import { generateID } from "./common";

export const FormControlNames = {
  STEPCONTAINER: "step-container",
  INPUTTEXTFIELD: "text-field",
  INPUTMULTILINE: "multiline-text-field",
  CHECKBOX: "checkbox",
  RADIOGROUP: "radio-group",
  SELECTDROPDOWN: "select-drop-down",
  DATEFIELD: "date-field",
  TIMEFIELD: "time-field",
  FILEUPLOAD: "file-upload",
  IMAGEUPLOAD: "image-upload",
  TOGGLE: "toggle",
  CHECKLIST: "checklist",
  SIGNATURE: "signature",
  MULTICHOICES: "multi-choices",
  SCANCODE: "scan-code",
  VERIFIEDID: "verified-id",
  LABELFIELD: "label-field",
  HEADINGFIELD: "heading-field",
};

export const FormTextDataTypes = {
  TEXT: "text",
};
export const ControlItemType = {
  INPUT: 'input',
  SELECT: 'select',
  RADIO: 'radioCard',
  LABEL: 'label',
  HEADING: 'heading',
}

export const FormItemTypes = {
  CONTROL: "control",
  CONTAINER: "container",
};

export const FormPublishStatus = {
  DRAFT: "draft",
  PUBLISHED: "published",
};

export const FormContainerList = [
  {
    id: '',
    controlName: FormControlNames.STEPCONTAINER,
    displayText: "Workflow Step",
    itemType: FormItemTypes.CONTAINER,
    icon: "fa fa-building",
    heading: "Container Heading",
    subHeading: "Container SubHeading",
  },
];

export const FormControlList = [
  {
    id: '',
    controlName: FormControlNames.INPUTTEXTFIELD,
    displayText: "Text Field",
    label: "Text Field",
    itemType: FormItemTypes.CONTROL,
    dataType: FormTextDataTypes.TEXT,
    icon: "fas fa-text-height",
    required: false,
    category: "text-elements",
    containerId: '',
    xs: 12,
    key: '',
    keyValue: '',
    default: '', // TODO: need to be added
    options: '', // TODO: needs to be handled
    type: ControlItemType.INPUT
  },
  {
    id: '',
    controlName: FormControlNames.LABELFIELD,
    displayText: "LABEL FIELD",
    label: "Label Field",
    itemType: FormItemTypes.CONTROL,
    dataType: FormTextDataTypes.TEXT,
    icon: "fas fa-label",
    required: false,
    category: "text-elements",
    containerId: '',
    xs: 12,
    keyValue: '',
    key: '',
    type: ControlItemType.LABEL
  },
  {
    id: '',
    controlName: FormControlNames.HEADINGFIELD,
    displayText: "Heading",
    label: "Heading Field",
    itemType: FormItemTypes.CONTROL,
    dataType: FormTextDataTypes.TEXT,
    icon: "fas fa-label",
    required: false,
    category: "text-elements",
    containerId: '',
    xs: 12,
    keyValue: 'Key Value',
    key: '',
    type: ControlItemType.HEADING
  },
  // {
  //   id: '',
  //   controlName: FormControlNames.INPUTMULTILINE,
  //   displayText: "Notes",
  //   description: "Some Description about the field",
  //   placeholder: "Please write your notes here.",
  //   label: "Notes",
  //   rows: 4,
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "far fa-file",
  //   required: false,
  //   category: "text-elements",
  //   containerId: '',
  // },
  // {
  //   id: '',
  //   controlName: FormControlNames.RADIOGROUP,
  //   displayText: "Radio",
  //   description: "Some Description about the field",
  //   label: "Label for Radio",
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "far fa-dot-circle",
  //   required: false,
  //   items: [
  //     {
  //       id: generateID(),
  //       value: "Button__-1",
  //       label: "Button 1",
  //     },
  //     {
  //       id: generateID(),
  //       value: "Button__-2",
  //       label: "Button 2",
  //     },
  //   ],
  //   category: "other-elements",
  //   containerId: '',
  // },
  // {
  //   id: '',
  //   controlName: FormControlNames.TOGGLE,
  //   displayText: "Toggle",
  //   description: "Some Description about the field",
  //   label: "Label for Toggle",
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "fas fa-toggle-on",
  //   required: false,
  //   category: "other-elements",
  //   containerId: '',
  // },
  // {
  //   id: '',
  //   controlName: FormControlNames.CHECKLIST,
  //   displayText: "Checklist",
  //   description: "Some Description about the field",
  //   label: "Label for Checklist",
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "fas fa-tasks",
  //   required: false,
  //   items: [
  //     {
  //       id: generateID(),
  //       value: "Check__-1",
  //       label: "Check 1",
  //     },
  //     {
  //       id: generateID(),
  //       value: "Check__-2",
  //       label: "Check 2",
  //     },
  //   ],
  //   category: "other-elements",
  //   containerId: '',
  // },
  // {
  //   id: '',
  //   controlName: FormControlNames.SELECTDROPDOWN,
  //   displayText: "Dropdown",
  //   description: "Some Description about the field",
  //   label: "Label for Dropdown",
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "far fa-caret-square-down",
  //   required: false,
  //   items: [
  //     {
  //       id: generateID(),
  //       value: "Option__-1",
  //       label: "Option 1",
  //     },
  //     {
  //       id: generateID(),
  //       value: "Option__-2",
  //       label: "Option 2",
  //     },
  //   ],
  //   category: "other-elements",
  //   containerId: '',
  // },
  // {
  //   id: '',
  //   controlName: FormControlNames.CHECKBOX,
  //   displayText: "Checkbox",
  //   description: "Some Description about the field",
  //   label: "Label for Checkbox",
  //   placeholder: "Place Holder Text",
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "far fa-check-square",
  //   required: false,
  //   category: "other-elements",
  //   containerId: '',
  // },
  // {
  //   id: '',
  //   controlName: FormControlNames.DATEFIELD,
  //   displayText: "Date Picker",
  //   description: "Some Description about the field",
  //   label: "Label for Date",
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "far fa-calendar",
  //   required: false,
  //   category: "date-elements",
  //   containerId: '',
  // },
  // {
  //   id: '',
  //   controlName: FormControlNames.TIMEFIELD,
  //   displayText: "Time",
  //   description: "Some Description about the field",
  //   label: "Label for Time",
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "far fa-clock",
  //   required: false,
  //   category: "date-elements",
  //   containerId: '',
  // },
  // {
  //   id: '',
  //   controlName: FormControlNames.SIGNATURE,
  //   displayText: "Signature",
  //   description: "Some Description about the field",
  //   label: "Label for Signature",
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "fa fa-signature",
  //   required: false,
  //   category: "other-elements",
  //   containerId: '',
  // },
  // {
  //   id: '',
  //   controlName: FormControlNames.FILEUPLOAD,
  //   displayText: "Upload",
  //   description: "Some Description about the field",
  //   label: "Label for File Upload",
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "fas fa-cloud-upload-alt",
  //   required: false,
  //   category: "media-elements",
  //   containerId: '',
  // },
  // {
  //   id: '',
  //   controlName: FormControlNames.IMAGEUPLOAD,
  //   displayText: "Image",
  //   description: "Some Description about the field",
  //   label: "Label for Image Upload",
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "far fa-image",
  //   required: false,
  //   category: "media-elements",
  //   containerId: '',
  // },
];
